---
title: "Schedule"
---

<style>

.schedule colgroup col {
    width: auto !important;
}

.schedule th {
  text-align: left;
}

.schedule th:nth-child(1),
.schedule th:nth-child(2) {
  width: 10%;
}

.schedule th:nth-child(3) {
  width: 45%;
}

.schedule th:nth-child(4) {
  width: 35%;
}

.schedule body {
  padding: 1rem;
}

.schedule tr:nth-child(4n),
.schedule tr:nth-child(4n-1){
    background: lightgrey;
}

.schedule tr:nth-child(12),
.schedule tr:nth-child(19),
.schedule tr:nth-child(25){
  background: #333333;
  color: white;
}

</style>

The following schedule is subject to change based on the progress of the class. Please check back frequently!

<div class = "schedule">
| **Date** | **Day** | **Topic**  | **Assignment Out** |
| ---------|---------|------------|--------------------|
04-Sep | Thur.  | Introduction  |A1: Real-World Objects|
09-Sep | Tues.  | Getting started with VSCode + git  | |
11-Sep | Thur.  | Object-Oriented Thinking   | A2: Object-ification|
16-Sep | Tues.  | Introduction to Java |  |
18-Sep | Thur.  | Software Engineering Skill: Requirements and Interfaces   | A3: Chatbot |
23-Sep | Tues.  | Encapsulation  | |
25-Sep | Thur.  | Association  |  A4: Chugging Along |
30-Sep | Tues.  | Memory Model Diagrams  ||
02-Oct | Thur.  | Handling Exceptions  | A5: Trace the Execution |
07-Oct | Tues.  | Software Engineering Skill: Unit Testing (pt1) | |
09-Oct | Thur.  | Software Engineering Skill: Unit Testing (pt2) | A6: Unit Testing |
14-Oct | Tues.  | CLASSES CANCELLED - Fall Recess | |
16-Oct | Thur.  | Real-World Application: Introduction to Graphics | Assignment Rewind |
21-Oct | Tues.  | Mid-semester Recap / AMA | |
23-Oct | Thur.  | Midterm Skill Check (No Class)  |  |
28-Oct | Tues.  | Inheritance  | |
30-Oct | Thur.  | Exploring Inheritance in Java Classes  | A7: Use What Your Parent (Class) Gave You |
04-Nov | Tues.  | Polymorphism pt. 1: Method Overriding  |  |
06-Nov | Thur.  | CLASSES CANCELLED - Cromwell Day | A8: Not Your Parent's Method |
11-Nov | Tues.  | Polymorphism pt. 2: Method Overloading  | |
13-Nov | Thur.  | Abstraction: Generics and Abstract Classes | FP1: Project Proposal |
18-Nov | Tues.  | Final Project Workshop 1  |   |
20-Nov | Thur.  | Software Engineering Skill: Architecture Diagrams  | FP2: Draft Codebase, Architecture Diagram |
25-Nov | Tues.  | Final Project Workshop + Code Review  |  |
27-Nov | Thur.  | CLASSES CANCELLED - Thanksgiving Recess | |
02-Dec | Tues.  | Real World Application: Data Structures  |  |
04-Dec | Thur.  | Final Project Workshop + Code Review | FP3: Revised Codebase, Architecture Diagram |
09-Dec | Tues.  | Real World Application: TBD |  |
11-Dec | Thur.  | Final Project Demonstration Day  | FP4: Final Deliverables (Due end of finals) |
</div>