---
title: "Schedule"
---

<style>

.table-condensed colgroup col {
    width: auto !important;
}

.table-condensed th {
  text-align: left;
}

.table-condensed th:nth-child(1),
.table-condensed th:nth-child(2) {
  width: 10%;
}

.table-condensed th:nth-child(3) {
  width: 45%;
}

.table-condensed th:nth-child(4) {
  width: 35%;
}

.table-condensed body {
  padding: 1rem;
}

.table-condensed tr:nth-child(4n-1), 
.table-condensed tr:nth-child(4n-2) {
    background: lightgrey;
}

.table-condensed tr:nth-child(10),
.table-condensed tr:nth-child(15),
.table-condensed tr:nth-child(17),
.table-condensed tr:nth-child(23){
  background: #333333;
  color: white;
}

</style>

The following schedule is subject to change based on the progress of the class. Please check back frequently!

| **Date** | **Day** | **Topic**  | **Assignment Out** |
| ---------|----------|------------|----------------|
9/7   | Thur. | Introduction | A1: Real-World Objects |
9/12  | Tues. | Getting started with VSCode + git ||
9/14  | Thur. | Object-Oriented Thinking  | A2: Object-ification |
9/19  | Tues. | Software Engineering Skill: Translating to/from Pseudocode ||
9/21  | Thur. | Introduction to Java | A3: Our First Java Class |
9/26  | Tues. | Encapsulation in Java  ||
9/28  | Thur. | Memory Models | A4: Trace the Execution |
10/3  | Tues. | Exceptions ||
10/5  | Thur. | Association pt. 1: Aggregation |Assignment Rewind: Revise & Resubmit|
10/10 | Tues. | No Class - Fall Break ||
10/12 | Thur. | Association pt. 2: Composition |A5: Assembling the Pieces|
10/17 | Tues. | Inheritance ||
10/19 | Thur. | Exploring Inheritance in Java Classes |A6: Use What Your Parent (Class) Gave You |
10/24 | Tues. | Mid-semester Recap / AMA ||
10/26 | Thur. | Midterm Skill Check (No Class) ||
10/31 | Tues. | Software Engineering Skill: Unit Testing |Assignment Rewind: Edge Cases & Testing |
11/2  | Thur. | No Class - Cromwell Day
11/7  | Tues. | Polymorphism pt. 1: Method Overriding ||
11/9  | Thur. | Polymorphism pt. 2: Method Overloading |A7: Not Your Parent's Method|
11/14 | Tues. | Abstraction pt. 1: Interfaces and Generic Types ||
11/16 | Thur. | Abstraction pt. 2: Abstract Classes ||
11/21 | Tues. | Final Project Workshop 1 | FP1: Project Proposal|
11/23 | Thur. | No Class - Thanksgiving Break ||
11/28 | Tues. | Software Engineering Skill: Architecture Diagrams | FP2: Draft Codebase, Architecture Diagram 
11/30 | Thur. | Real World Applications pt. 1||
12/5  | Tues. | Final Project: Code Review |FP3: Beta Codebase, Revised Architecture Diagram|
12/7  | Thur. | Real World Applications pt. 2 ||
12/12 | Tues. | Final Project Workshop 2 ||
12/14 | Thur. | Final Project Presentations ||
